In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [15]:
info = pd.read_csv('Churn_Modelling.csv')

In [16]:
info.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [17]:
info.shape

(10000, 14)

In [19]:
x = info.iloc[:,3:-1]
y = info.iloc[:,-1]


lc = LabelEncoder()
x['Gender'] = lc.fit_transform(x['Gender']) 


ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = ct.fit_transform(x)


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=64)

In [35]:
x[:,4]

array([0., 0., 0., ..., 0., 1., 0.])

In [21]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [28]:
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units = 11, activation='relu'))
ann.add(tf.keras.layers.Dense(units = 5, activation='relu'))
ann.add(tf.keras.layers.Dense(units = 1, activation='sigmoid'))

In [29]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(x_train, y_train, batch_size = 64, epochs = 101) 

Epoch 1/101
118/118 [==============================] - 1s 2ms/step - loss: 0.6415 - accuracy: 0.6808
Epoch 2/101
118/118 [==============================] - 0s 2ms/step - loss: 0.4814 - accuracy: 0.7979
Epoch 3/101
118/118 [==============================] - 0s 3ms/step - loss: 0.4532 - accuracy: 0.8029
Epoch 4/101
118/118 [==============================] - 0s 2ms/step - loss: 0.4391 - accuracy: 0.8079
Epoch 5/101
118/118 [==============================] - 0s 2ms/step - loss: 0.4310 - accuracy: 0.8103
Epoch 6/101
118/118 [==============================] - 0s 2ms/step - loss: 0.4250 - accuracy: 0.8143
Epoch 7/101
118/118 [==============================] - 0s 2ms/step - loss: 0.4203 - accuracy: 0.8192
Epoch 8/101
118/118 [==============================] - 0s 2ms/step - loss: 0.4161 - accuracy: 0.8217
Epoch 9/101
118/118 [==============================] - 0s 2ms/step - loss: 0.4124 - accuracy: 0.8240
Epoch 10/101
118/118 [==============================] - 0s 2ms/step - loss: 0.4089 - accura

In [39]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

1/1 [==============================] - 0s 120ms/step


array([[0.]], dtype=float32)

In [46]:
y_pred = (ann.predict(x_test) > 0.7)

79/79 [==============================] - 0s 1ms/step


In [47]:
confusion_matrix(y_test, y_pred)

array([[1693,  313],
       [ 380,  114]])

In [48]:
accuracy_score(y_test, y_pred)

0.7228